# Generated by Django 3.1.5 on 2021-01-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardBillFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=None)),
            ],
        ),
        migrations.AddField(
            model_name='creditcardrecord',
            name='file',
            field=models.CharField(default='Example', max_length=80),
            preserve_default=False,
        ),
    ]
