# Generated by Django 3.1.5 on 2021-01-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0002_auto_20210117_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardrecord',
            name='installment_total',
            field=models.IntegerField(),
        ),
    ]
